language: node_js

os:
  - linux
  - windows

node_js:
  - 6
  - 8
  - 10

cache:
  directories:
    - node_modules

script:
  - node ./bin/cake build:except-parser
  - node ./bin/cake build:parser
  - node ./bin/cake build:full
  - node ./bin/cake build:browser
  - node ./bin/cake test
  - node --harmony ./bin/cake test
  - node ./bin/cake test:browser
  - node ./bin/cake test:integrations
